spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.100.12:3306/S90?Unicode=true&amp;characterEncoding=UTF-8
      username: root
      password: dfS6zS*d
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.100.12:3306/S90?Unicode=true&amp;characterEncoding=UTF-8
      username: root
      password: dfS6zS*d
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.100.12:3306/S90?Unicode=true&amp;characterEncoding=UTF-8
      username: root
      password: dfS6zS*d
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl