spring:
  datasource:
    master:
      url: jdbc:mysql://192.168.111.12:3306/S90?Unicode=true&amp;characterEncoding=UTF-8
      username: root
      password: 111111
      driverClassName: com.mysql.jdbc.Driver
    slave[0]:
      url: jdbc:mysql://192.168.111.12:3306/S90?Unicode=true&amp;characterEncoding=UTF-8
      username: root
      password: 11111
      driverClassName: com.mysql.jdbc.Driver
    slave[1]:
      url: jdbc:mysql://192.168.111.12:3306/S90?Unicode=true&amp;characterEncoding=UTF-8
      username: root
      password: 11111
      driverClassName: com.mysql.jdbc.Driver

server:
  port: 8000
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl